### ISSUE TITLE
Invalid CVSS v3 environmental score computation

### ISSUE THREAD

**Issue by pandatix** [goark/go-cvss#18]
Still while fuzzing the implementation, I discovered that environmental scores were not computed properly, leading to invalid scores.
For instance, the following Go code computes the three scores and prints them.
```go
package main

import (
	"fmt"
	"log"

	"github.com/goark/go-cvss/v3/metric"
)

func main() {
	vec, err := metric.NewEnvironmental().Decode("CVSS:3.1/AV:A/AC:H/PR:L/UI:N/S:U/C:H/I:L/A:N/MS:C")
	if err != nil {
		log.Fatal(err)
	}

	b, t, e := vec.Base.Score(), vec.Temporal.Score(), vec.Score()
	fmt.Printf("Scores: %.1f;%.1f;%.1f\n", b, t, e)
}
```
produces ->
```
Scores: 5.4;5.4;6.4
```
You can check this input is valid, [using the official first.org calculator](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N/RL:O) but then computes an environmental score of 6.5.

**Comment by spiegel-im-spiegel** [comment]
Relese [v1.4.4](https://github.com/goark/go-cvss/releases/tag/v1.4.4)
